name: Validate Extensions

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('global.json', 'build/**/*.csproj', 'build/**/*.props', 'build/**/*.targets') }}

      - name: 'Run: GenerateManifest'
        run: ./build.cmd GenerateManifest
